package com.CyberSoft.uniclubWeb.service;

import com.CyberSoft.uniclubWeb.entity.*;
import com.CyberSoft.uniclubWeb.repository.*;
import com.CyberSoft.uniclubWeb.service.imp.FakeDataServiceImp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Random;

@Service
public class FakeDataService implements FakeDataServiceImp {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private RoleRepository roleRepository;

    @Autowired
    private ReviewRepository reviewRepository;

    @Autowired
    private WishlistRepository wishlistRepository;

    private final Random random = new Random();

    @Override
    public void generateFakeData() {
        generateRoles(5); // Tạo 5 vai trò giả
        generateUsers(10); // Tạo 10 người dùng giả
        generateProducts(20); // Tạo 20 sản phẩm giả
        // generateReviews(15); // Tạo 15 đánh giá giả
        // generateWishlists(10); // Tạo 10 wishlist giả
    }

    @Override
    public void generateRoles(int count) {
        for (int i = 1; i <= count; i++) { 
            RoleEntity role = new RoleEntity(); // Tạo một đối tượng mới trong mỗi lần lặp
    
            switch (i) {
                case 1:
                    role.setName("ADMIN");
                    break;
                case 2:
                    role.setName("SELLER");
                    break;
                case 3:
                    role.setName("CUSTOMER");
                    break;
                case 4:
                    role.setName("STAFF");
                    break;
                default:
                    role.setName("GUEST");
                    break;
            }
    
            roleRepository.save(role); // Lưu vào database
        }
    }
    

    @Override
    public void generateUsers(int count) {
        for (int i = 1; i <= count; i++) {
            UserEntity user = new UserEntity();
            user.setFullName("User " + i);
            user.setEmail("user" + i + "@example.com");
            user.setPassword("password" + i);
            user.setCreatedAt("2025-03-24");
            user.setUpdatedAt("2025-03-25");
            user.setUpdatedBy("Admin");
            user.setStatus("active");
            user.setLastChangeNote("Generated by FakeDataService");
            user.setRole(roleRepository.findById(random.nextInt(3) + 1).orElse(null)); // Gán vai trò ngẫu nhiên
            userRepository.save(user);
        }
    }

    @Override
    public void generateProducts(int count) {
        for (int i = 1; i <= count; i++) {
            ProductEntity product = new ProductEntity();
            product.setProductName("Product " + i);
            product.setPrice(random.nextInt(1000) + 100); // Giá từ 100 đến 1100
            product.setSku("SKU" + i);
            product.setDescription("Description for Product " + i);
            product.setInformation("Information for Product " + i);
            product.setImages("image" + i + ".jpg");
            product.setCreatedAt("2025-03-24");
            product.setUpdatedAt("2025-03-24");
            product.setUpdatedBy("Admin");
            product.setStatus("active");
            product.setLastChangeNote("Initial creation");
            productRepository.save(product);
        }
    }

    // @Override
    // public void generateReviews(int count) {
    //     for (int i = 1; i <= count; i++) {
    //         ReviewEntity review = new ReviewEntity();
    //         review.setAvatarCustomer("avatar" + i + ".jpg");
    //         review.setNameCustomer("Customer " + i);
    //         review.setEmailCustomer("customer" + i + "@example.com");
    //         review.setReviewContent("This is a review for product " + i);
    //         review.setProduct(productRepository.findById(random.nextInt(20) + 1).orElse(null)); // Gán sản phẩm ngẫu nhiên
    //         reviewRepository.save(review);
    //     }
    // }

    // @Override
    // public void generateWishlists(int count) {
    //     for (int i = 1; i <= count; i++) {
    //         WishlistEntity wishlist = new WishlistEntity();
    //         wishlist.setProduct(productRepository.findById())
    //         // wishlist.setProduct(productRepository.findById(random.nextInt(20) + 1).orElse(null)); // Gán sản phẩm ngẫu nhiên
    //         // wishlist.setUser(userRepository.findById(random.nextInt(10) + 1).orElse(null)); // Sửa lỗi từ "setUserId" thành "setUser"
    //         // wishlist.setStockStatus(random.nextInt(2)); // 0 hoặc 1
    //         wishlistRepository.save(wishlist);
    //     }
    // }
}
